import 'package:flutter/material.dart';
const Map<String, List<Map<int, Object>>> breatheChains = {
  'fullBody': [
    {0: 'Find a place to sit or lie down\n\nRest one arm on your chest and one on your abdomen', 1: Color(0xFF76A487)},
    {0: 'Focus on your toes\n\nWiggle them back and forth', 1: Color(0xFFE5AD5A)},
    {0: 'Move your attention up through your feet to your ankles', 1: Color(0xFFBDD4DA)},
    {0: 'Notice your lower legs\n\nDo you feel any tension?', 1: Color(0xFFC69167)},
    {0: 'Settle your awareness into your knees', 1: Color(0xFF9CC4A9)},
    {0: 'Feel the muscles in your thighs\n\nNotice how they press into the surface you are resting on', 1: Color(0xFF5491A3)},
    {0: 'Place your awareness in your hips\n\nFeel the weight of your body supported here', 1: Color(0xFF76A487)},
    {0: 'Find your lower back\n\nSee if you can notice your breath in this space', 1: Color(0xFFE5AD5A)},
    {0: 'Breathe through your upper back and shoulders\n\nRelease any tension you discover', 1: Color(0xFFBDD4DA)},
    {0: 'Move down your arms to your elbows', 1: Color(0xFFC69167)},
    {0: 'Feel your forearms resting gently on your body', 1: Color(0xFF9CC4A9)},
    {0: 'Notice your breath in your hands', 1: Color(0xFF5491A3)},
    {0: 'Fill your belly with air, feel it rise and fall', 1: Color(0xFF76A487)},
    {0: 'Notice the way your chest moves with each inhale', 1: Color(0xFFE5AD5A)},
    {0: 'Find your breath in your throat, feel it move through your nose', 1: Color(0xFFBDD4DA)},
    {0: 'Relax the muscles in your face, feel your head fill the space', 1: Color(0xFFC69167)},
    {0: 'Continue to take deep breaths, feeling the air move through you', 1: Color(0xFF9CC4A9)},
    {0: 'Stay here for as long as you need\n\nWhen you\'re ready, open your eyes and notice the world around you', 1: Color(0xFF5491A3)},
    {0: 'You are capable of amazing things\n\nRemember to have compassion for yourself', 1: Color(0xFF76A487)},
  ],
  'lowerBody': [
    {0: 'Find a place to sit or lie down\n\nRest one arm on your chest and one on your abdomen', 1: Color(0xFF76A487)},
    {0: 'Focus on your toes\n\nWiggle them back and forth', 1: Color(0xFFE5AD5A)},
    {0: 'Move your attention up through your feet to your ankles', 1: Color(0xFFBDD4DA)},
    {0: 'Notice your lower legs\n\nDo you feel any tension?', 1: Color(0xFFC69167)},
    {0: 'Settle your awareness into your knees', 1: Color(0xFF9CC4A9)},
    {0: 'Feel the muscles in your thighs\n\nNotice how they press into the surface you are resting on', 1: Color(0xFF5491A3)},
    {0: 'Place your awareness in your hips\n\nFeel the weight of your body supported here', 1: Color(0xFF76A487)},
    {0: 'Stay here for as long as you need\n\nWhen you\'re ready, open your eyes and notice the world around you', 1: Color(0xFF5491A3)},
    {0: 'You are capable of amazing things\n\nRemember to have compassion for yourself', 1: Color(0xFF76A487)},
  ],
  'torso': [
    {0: 'Find a place to sit or lie down\n\nRest one arm on your chest and one on your abdomen', 1: Color(0xFF76A487)},
    {0: 'Find your lower back\n\nSee if you can notice your breath in this space', 1: Color(0xFFE5AD5A)},
    {0: 'Breathe through your upper back and shoulders\n\nRelease any tension you discover', 1: Color(0xFFBDD4DA)},
    {0: 'Move down your arms to your elbows', 1: Color(0xFFC69167)},
    {0: 'Feel your forearms resting gently on your body', 1: Color(0xFF9CC4A9)},
    {0: 'Notice your breath in your hands', 1: Color(0xFF5491A3)},
    {0: 'Fill your belly with air, feel it rise and fall', 1: Color(0xFF76A487)},
    {0: 'Stay here for as long as you need\n\nWhen you\'re ready, open your eyes and notice the world around you', 1: Color(0xFF5491A3)},
    {0: 'You are capable of amazing things\n\nRemember to have compassion for yourself', 1: Color(0xFF76A487)},
  ],
  'upperBody': [
    {0: 'Find a place to sit or lie down\n\nRest one arm on your chest and one on your abdomen', 1: Color(0xFF76A487)},
    {0: 'Notice the way your chest moves with each inhale', 1: Color(0xFFE5AD5A)},
    {0: 'Find your breath in your throat, feel it move through your nose', 1: Color(0xFFBDD4DA)},
    {0: 'Relax the muscles in your face, feel your head fill the space', 1: Color(0xFFC69167)},
    {0: 'Continue to take deep breaths, feeling the air move through you', 1: Color(0xFF9CC4A9)},
    {0: 'Stay here for as long as you need\n\nWhen you\'re ready, open your eyes and notice the world around you', 1: Color(0xFF5491A3)},
    {0: 'You are capable of amazing things\n\nRemember to have compassion for yourself', 1: Color(0xFF76A487)},
  ],
};
